### PR TITLE
Bump versions, fixes, doc updates.

### LINKED ISSUE #619: Pedestal dependencies have CVEs of high/critical severity
# Description
I ran `dependency-check-maven` on the pom.xml generated by a tools.deps project using `clj -Spom`. The report attached contains the results showing evidence that several pedestal dependencies related to jetty contains high/critical severity. The report is zipped because github do not accept html attachments.
[dependency-check-report.html.zip](https://github.com/pedestal/pedestal/files/3214978/dependency-check-report.html.zip)

Updating jetty dependencies to the latest did not broke tests on my project and are not affected by those vulnerabilities.

## Expected Behavior
Pedestal dependencies should not have know CVEs of high/critical severity

## Actual Behavior
Pedestal dependencies have CVEs of high/critical severity

## Steps to reproduce
Run dependency-check-maven with the pom generated by tools.deps using `clj -Spom` on a project with only pedestal as dependency. I used the configuration on example 1 on this page: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/

# Environment

## Operating System (including version).
Arch Linux

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
`clj`

## Pedestal version
0.5.5

### PR DESCRIPTION
**Pull request by ddeaguiar**
- Bumps project dependencies.
  - There were a number of vulnerabilities reported for the previous Jetty
    version as per the OWASP Dependency Check tool 
    (https://www.owasp.org/index.php/OWASP_Dependency_Check). Changes were benchmarked 
    locally using `lein benchmark-service` + `service/bin/perfit.sh` and showed no significant 
    difference.
- Jetty HttpConfiguration can now be set via `:container-options`.

Resolves #619, #615.

### CODE REVIEW

**Comment by ddeaguiar** [comment]
@ohpauleez good idea. I was planning on cutting a release after these changes landed as well.

**Comment by ohpauleez** [comment]
I would like to see this issue fixed before the release: https://github.com/pedestal/pedestal/issues/615

In summary, the `http-configuration` should also destructure a `:http-configuration` option, which will short-circuit the function and return that configuration.

**Comment by ohpauleez** [comment]
Let's also address: https://github.com/pedestal/pedestal/pull/585 and https://github.com/pedestal/pedestal/pull/594

**Comment by ddeaguiar** [comment]
👍

**Comment by ddeaguiar** [comment]
I've bumped deps but still need to run some tests.

File: service/src/io/pedestal/http.clj [hunk 1]
```diff
@@ -363,11 +378,17 @@
       create-provider ;; Creates/connects a backend to the interceptor chain
       server)))
 
-(defn start [service-map]
+(defn start
+  "Given service-map, an initialized service map returned by `create-server`,
+  invokes the zero-arg function assoc'd to the service map via `:io.pedestal.http/start-fn.`"
```
Comment (ohpauleez) [inline service/src/io/pedestal/http.clj]: Just needs:  "Returns the `service-map` on success."

File: service/src/io/pedestal/http.clj [hunk 2]
```diff
@@ -363,11 +378,17 @@
...
+  [service-map]
   ((::start-fn service-map))
   service-map)
 
-(defn stop [service-map]
+(defn stop
+  "Given service-map, an initialized service map returned by `create-server`,
+  invokes the zero-arg function assoc'd to the service map via `:io.pedestal.http/stop-fn.`"
```
Comment (ohpauleez) [inline service/src/io/pedestal/http.clj]: Just needs "Returns `service-map` on success"
